/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-nouradio_test
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_NOURADIO_TEST_API_H
#define INCLUDED_NOURADIO_TEST_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_nouradio_test_EXPORTS
#define NOURADIO_TEST_API __GR_ATTR_EXPORT
#else
#define NOURADIO_TEST_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_NOURADIO_TEST_API_H */
